spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:15432/app
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080